repro: attempt to depend on Go library that has BUILD files
Error: error loading package '@@gazelle~~go_deps~build_aspect_cli//bazel/buildeventstream': at /private/var/tmp/_bazel_alexeagle/30b0e7ef1c27a33f59c0ac0dbf52b21b/external/gazelle~~go_deps~build_aspect_cli/bazel/go/write_go_generated_source_files.bzl:7:6: Unable to find package for @@[unknown repo 'aspect_bazel_lib' requested from @@gazelle~~go_deps~build_aspect_cli]//lib:directory_path.bzl: The repository '@@[unknown repo 'aspect_bazel_lib' requested from @@gazelle~~go_deps~build_aspect_cli]' could not be resolved: No repository visible as '@aspect_bazel_lib' from repository '@@gazelle~~go_deps~build_aspect_cli'. and referenced by '//backend/cmd/plugin:plugin_lib'